SELECT
    Account.PersonContactId AS ContactKey,
    Account.Id AS 'Account Id',
    Account.cel_ext_account_id__c AS 'External Id',
    Account.Salutation AS Title,
    Account.LastName AS Lastname,
    Account.Firstname AS Firstname,
    Account.cel_lastname_local_2__c AS 'Lastname Local',
    Account.cel_firstname_local_2__c AS 'Firstname Local',
    Account.cel_addr_1_validity__c AS 'Address 1 Validity',
    Account.cel_addr_1_line_1__c AS 'Address 1 Line 1',
    Account.cel_addr_1_line_2__c AS 'Address 1 Line 2',
    Account.cel_addr_1_line_3__c AS 'Address 1 Line 3',
    Account.cel_addr_1_zipcode__c AS 'Address 1 PostCode',
    Account.cel_addr_1_region__c AS 'Address 1 State Province',
    Account.cel_addr_1_city__c AS 'Address 1 City',
    Account.cel_addr_1_country__c AS 'Address 1 Country',
    Account.PersonMobilePhone AS 'Mobile Phone',
    Account.PersonDoNotCall AS 'Mobile Optin',
    Account.cel_mobile_validity__c AS 'Mobile Validity',
    Account.PersonEmail AS Email,
    Account.cel_do_not_email__c AS 'Email Optin',
    Account.cel_second_email_optin__c AS 'Email Optin 2',
    Account.cel_birthdate_day__c AS 'Birthdate Day',
    Account.cel_birthdate_month__c AS 'Birthdate Month',
    Account.cel_birthdate_year__c AS 'Birthdate Year',
    Account.cel_customer_store_code_creation__c AS 'Creation Store',
    Account.cel_customer_main_store__c AS 'Main Store',
    Account.cel_region_main_store__c AS 'Region Main Store',
    Account.Type AS 'Customer Type',
    Account.cel_origine__c AS 'Origin',
    Account.cel_main_SA__c AS 'Main SA Contact Id',
    Account.cel_nationality__c AS 'Nationality',
    Account.cel_local_customer__c AS 'Customer Local',
    Account.cel_segmentation__c AS 'Current Segmentation',
    Account.cel_segmentation_last_month__c AS 'Previous Segmentation',
    Account.cel_distance_nearest_store__c AS 'Distance of nearest store',
    Account.cel_FLEN_Active__c AS 'Flag Flen',
    Account.cel_sent_by_sfcm__c AS 'IsMCcust',
    Account.cel_creation_date__c AT TIME ZONE 'Central America Standard Time' AT TIME ZONE 'GMT Standard Time' AS 'Local Creation Date',
    Account.CreatedDate AT TIME ZONE 'Central America Standard Time' AT TIME ZONE 'GMT Standard Time' AS 'Salesforce Creation Date',
    Account.LastModifiedDate AT TIME ZONE 'Central America Standard Time' AT TIME ZONE 'GMT Standard Time' AS 'Salesforce Last Update Date',
    Contact.FirstName AS 'Main SA Firstname',
    Contact.LastName AS 'Main SA Lastname',
    Account.cel_FLEN__c AS 'Flen',
    Account.cel_prefered_communication_language__c AS 'Language',
    Contact.cel_ext_sale_associate_code__c AS 'Main SA Cegid Id',
    SUBSTRING (Account.cel_customer_main_store__c, 1, 2) AS 'Country Main Store',
    Account.cel_id_check__c AS 'IDCheck'
FROM
    ENT.ACCOUNT_SALESFORCE_1 AS Account
    LEFT OUTER JOIN ENT.CONTACT_SALESFORCE_1 AS Contact ON Account.cel_main_SA__c = Contact.Id
WHERE
    Account.RecordTypeId = '0121r0000007NppAAE'
    AND Account.cel_ext_account_id__c IS NOT NULL